services:
  api:
    build:
      context: .
      dockerfile: ./docker/uv/Dockerfile
    container_name: carekobot
    depends_on:
      kokoro:
        condition: service_started
    environment:
      BOT_DEFAULT_PREFIX: ${BOT_DEFAULT_PREFIX}
      BOT_TTS_API_URL: ${BOT_TTS_API_URL}
      BOT_TTS_VOICE_MODEL: ${BOT_TTS_VOICE_MODEL}
      BOT_DISCORD_TOKEN: ${BOT_DISCORD_TOKEN}
    entrypoint: ["python", "-m", "src.carekobot.main"]
    restart: unless-stopped

  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    container_name: carekobot_kokoro
    ports:
      - "8880:8880"
    restart: unless-stopped
