services:
  api:
    build:
      context: .
      dockerfile: ./docker/uv/Dockerfile
    container_name: carekobot
    depends_on:
      kokoro:
        condition: service_started
    environment:
      TTS_HOST: ${TTS_HOST}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    entrypoint: ["python", "-m", "src.carekobot.main"]
    restart: unless-stopped

  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    container_name: carekobot_kokoro
    ports:
      - "8880:8880"
    restart: unless-stopped
